avigad/mathematics_in_lean_source

source/basic_skills.rst

The chapter is deployed to leanprover-community, so you can also read it in html or pdf: https://leanprover-community.github.io/mathematics_in_lean/

finish draft of basic skills chapter

---

leanpkg.toml
source/basic_skills.rst
source/basics.rst
source/index.rst
source/introduction.rst
source/logic.rst

* Added a section on negation
* Adding the uniqueness of limits to the last section on the logic chapter.
* Renamed "Basic Skills" to "Basics"
As usual, the draft is here: https://avigad.github.io/mathematics_in_lean/
All that is left for this chapter is a section on conjunction/iff, and a section on disjunction.

section on negation

---

source/basics.rst

Line with `add_lt_add_of_le_of_lt ` should be changed to `add_lt_add_of_lt_of_le`

Changed duplicated line

---

source/basics.rst
source/introduction.rst
source/logic.rst

This is a bunch of things I noticed while reading yesterday and felt were simple enough to improve without opening an issue first. I don't think there is anything I feel strongly about so don't hesitate to argue against some. Sometimes I may be adding too many details.

Some corrections and precisions

---

source/introduction.rst

mathematicians might be more familiar with the ∧ symbol than this mathematically nonstandard X -> Y -> Z

reword FLT

---

source/introduction.rst

Two suggestions -- I'm happy to be overruled. First, adding comments in tactic code I think makes it even easier to orientate yourself. Second, `mul_right_comm` or whatever it's called is something I tend not to fuss too much about: using a one size fits all tactic is much easier.

suggestion of alternative proof

---

source/logic.rst
source/sets_functions_and_relations.rst

This addresses some of things that needed to be done, but not all of them. Two things still open:
- Exercises with images and preimages of bounded and indexed unions.
- Examples of the choose tactic.

misc improvements to sets, functions, and relations

---

source/basics.rst
source/logic.rst
source/sets_functions_and_relations.rst

These address a number of open issues. I think the remaining ones do not need to be addressed right away.

various improvements to sets, functions, and relations

---

source/sets_functions_and_relations.rst

I have fixed a few typos in your `inj_on` and `range` examples.  I also went ahead and added solutions to these examples as well.  I am just starting with lean so I am not sure how idiomatic my solutions are.
I have enjoyed working through the book!  I look forward to further additions.

Fix typos in inj_on and range examples

---

lean_source/02_Basics/source_01_Calculating.lean
lean_source/02_Basics/source_02_Proving_Identities_in_Algebraic_Structures.lean

Fixes #44 and also moves a misplaced import inside a code block.

Add import inside the code block.

---

lean_source/07_Topology/source_02_Metric_Spaces.lean

Corrected the proof sketch for uniformly continuous functions

Fix proof sketch

---

MIL/C02_Basics/Source_S01_Calculating.lean
MIL/C02_Basics/Source_S02_Proving_Identities_in_Algebraic_Structures.lean
MIL/C02_Basics/Source_S04_More_on_Order_and_Divisibility.lean
MIL/C03_Logic/Source_S01_Implication_and_the_Universal_Quantifier.lean
MIL/C03_Logic/Source_S02_The_Existential_Quantifier.lean
MIL/C03_Logic/Source_S03_Negation.lean
MIL/C03_Logic/Source_S04_Conjunction_and_Bi-implication.lean
MIL/C03_Logic/Source_S05_Disjunction.lean
MIL/C04_Sets_and_Functions/Source_S01_Sets.lean
MIL/C04_Sets_and_Functions/Source_S02_Functions.lean
MIL/C04_Sets_and_Functions/Source_S03_The_Schroeder_Bernstein_Theorem.lean
MIL/C05_Number_Theory/Source_S01_Irrational_Roots.lean
MIL/C05_Number_Theory/Source_S02_Induction_and_Recursion.lean
MIL/C05_Number_Theory/Source_S03_Infinitely_Many_Primes.lean
MIL/C06_Abstract_Algebra/Source_S01_Structures.lean
MIL/C06_Abstract_Algebra/Source_S02_Algebraic_Structures.lean
MIL/C06_Abstract_Algebra/Source_S03_Building_the_Gaussian_Integers.lean
source/C06_Abstract_Algebra.rst

Naming convention edits

---

MIL/C02_Basics/Source_S01_Calculating.lean

Suggested by Hannah Fechtner on Zulip

Fixes from Zulip

---

MIL/C06_Structures/Source_S03_Building_the_Gaussian_Integers.lean

(Not sure if this is defeating the point of the exercise.)

golf a proof in "Building the Gaussian Integers"

---

MIL/C08_Topology/Source_S03_Topological_Spaces.lean

this was already mentioned in the metric space section (with slightly more information).

remove duplicate sentence 

---

MIL/C09_Differential_Calculus/Source_S01_Elementary_Differential_Calculus.lean
MIL/C09_Differential_Calculus/Source_S02_Differential_Calculus_in_Normed_Spaces.lean

typos from ch9

---

.docker/gitpod/Dockerfile
.gitpod.yml
README.md
scripts/requirements.txt

In addition to the usual Lean setup, this dockerfile includes the python setup that is needed for `scripts/mkall.py`.

Add gitpod support to the source repo

---

.github/workflows/build.yml

CI won't run on this repo until you merge the PR, but you can see it running [on my fork here](https://github.com/eric-wieser/mathematics_in_lean_source/actions/runs/5997702659).

Add github CI, copied from std4

---

user_repo_source/README.md

tap this
gives
thus hope this simple PR fixes this

Super tiny fix link

---

MIL/C02_Basics/S02_Proving_Identities_in_Algebraic_Structures.lean

Thanks for fixing issue in https://github.com/avigad/mathematics_in_lean_source/issues/125, added the fix for the other such case.

Fully resolve #125

---

user_repo_source/README.md

Change "Lean 4: Open Documentation View" to "Lean 4: Docview: Open Docview"

Update README.md correct VS Code option to open documentation to "Lean 4: Docview: Open Docview"

---

MIL/C07_Hierarchies/S01_Basics.lean
MIL/C07_Hierarchies/S02_Morphisms.lean
MIL/C07_Hierarchies/S03_Subobjects.lean

This addresses some minor typos I came across.

fix: minor typos

---

MIL/C06_Structures/S02_Algebraic_Structures.lean
MIL/C06_Structures/S03_Building_the_Gaussian_Integers.lean

Less equal on partially ordered set is reflexive

---

MIL/C02_Basics/S01_Calculating.lean

Fix some inconsistencies - the doc refers to `nth_rewrite` but the code is using `nth_rw`, etc.
```
scripts/mkall.py
make html
```
Locally succeeded (on OSX), and the html looks good.

Fix minor inconsistency in S01_Calculating.lean

---

MIL/C05_Elementary_Number_Theory/S02_Induction_and_Recursion.lean

Hello, noticed a tiny typo. This PR fixes it.

C05/S02: fix typo

---

MIL/C02_Basics/S04_More_on_Order_and_Divisibility.lean
MIL/C02_Basics/S05_Proving_Facts_about_Algebraic_Structures.lean

Solutions in C02S04/05 use `repeat'` but this tactic is not described in the text and everything works fine with `repeat`.

replace repeat' with repeat in Chapter 02 solutions

---

MIL/C02_Basics/S02_Proving_Identities_in_Algebraic_Structures.lean
MIL/C06_Structures/S02_Algebraic_Structures.lean
MIL/C08_Groups_and_Rings/S01_Groups.lean
MIL/C09_Topology/S01_Filters.lean
MIL/C09_Topology/S02_Metric_Spaces.lean

This PR upgrades deprecated lemmas. None of them appears in the textual content.

Upgrade deprecated lemmas

---

MIL/C09_Linear_Algebra/S04_Bases.lean

Fixed an example so that it is about vector sum, not matrix sum.

Tiny fix in S04_Bases.lean

---

MIL/C02_Basics/S02_Proving_Identities_in_Algebraic_Structures.lean

The PR updated deprecated lemma in C02 S02.
Closes #295

Updated deprecated lemmas in 2.2

---

MIL/C06_Structures/S02_Algebraic_Structures.lean

Structures: update names to match new ones in mathlib
