- source/basic_skills.rst
- source/introduction.rst
This fixes a bunch of typos. I initially made two PRs to the mathematics_in_lean repo, when I wasn't aware of this source repo. This PR contains all the fixes of those two old PRs.
> Fix a bunch of typos

- to-be-deployed/README.md
Since https://github.com/leanprover-community/mathematics_in_lean is generated from this repo, the README there should direct potential contributors here.
> redirect contributors to this repo

- source/basics.rst
- source/conf.py
- source/index.rst
- source/introduction.rst
- source/logic.rst
- source/sets_functions_and_relations.rst
Up to now most entries are tactics, both listed alphabetically and all
together as subentries. But there are also a couple of mathematical
notions, partly for their own sake and partly as memory anchors when
people try to find back explanations about Lean (like: if I remember
correctly, this trick was explained while they were playing with
exponential...).
> Start building an index

- .gitignore
- lean_source/01_Introduction/source_01_Getting_Started.lean
- lean_source/06_Abstract_Algebra/source_01_Structures.lean
- lean_source/06_Abstract_Algebra/source_02_Algebraic_Structures.lean
- lean_source/mkall.sh
- source/06_Abstract_Algebra.rst
- source/index.rst
- user_repo/README.md
This is a start on chapter 6, which introduces abstract algebra. The opening section deals only with structures. The next section will introduce type class inference, and begin to explain how this is used to build hierarchy of structures.
> abstract algebra: draft of structures section

- lean_source/01_Introduction/source_02_Overview.lean
As per [the spec](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#embedded-uris-and-aliases).
> Fix reST link syntax

- lean_source/05_Number_Theory/source_03_Infinitely_Many_Primes.lean
We have `m` divides `n`, the remaining factor should be `n / m`, not the other way around.
> Reverse order of division.

- MIL/C02_Basics/Source_S01_Calculating.lean
The quoted example was referencing an import, but the import was not part of the rendered document (and happened to be repeated for some reason).
Also remove a variable that's declared but never used.
> Fix a minor prose error in the text.

- MIL/C06_Structures/Source_S03_Building_the_Gaussian_Integers.lean
- MIL/C08_Topology/Source_S01_Filters.lean
- MIL/C08_Topology/Source_S02_Metric_Spaces.lean
- MIL/C08_Topology/Source_S03_Topological_Spaces.lean
* Mostly using Lean 4 naming convention
* Also remove all occurrences of the unexplained notations `$` and `<|` in the book (not in all solutions)
> fix typos in topology chapter

- MIL/C06_Structures/S03_Building_the_Gaussian_Integers.lean
- MIL/C09_Differential_Calculus/S01_Elementary_Differential_Calculus.lean
- lake-manifest.json
- lean-toolchain
In this mathlib version, `lake exe cache get` uses `leantar`, which helps with cache corruption. See https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/an.20error for the motivation.
The relevant upstream PRs are leanprover-community/mathlib4#5944 and leanprover/lean4#2275.
(A patched-up version of the output repository is at https://github.com/leanprover-community/mathematics_in_lean/pull/9 for testing purposes, but I will close the PR there once it serves no debugging purpose.)
> chore: bump mathlib

- MIL/C03_Logic/S03_Negation.lean
- MIL/C04_Sets_and_Functions/S01_Sets.lean
- MIL/C04_Sets_and_Functions/S02_Functions.lean
- MIL/C05_Elementary_Number_Theory/S03_Infinitely_Many_Primes.lean
- lake-manifest.json
- lean-toolchain
This directly copies the mathlib lake-manifest.json for all the other dependencies.
It seems the `use` tactic became more powerful, and now uses `assumption` or similar to close stray goals.
Tested in gitpod (#104) to ensure that `lake build` passes.
> Update dependences to match mathlib

- MIL/C03_Logic/S04_Conjunction_and_Iff.lean
Remove confusing duplicate suggestion as le_antisymm isn't used.
> Text seem to imply we weren't allowed to use `le_trans`.

- .docker/gitpod/Dockerfile
- .gitpod.yml
As with all untested code, this didn't work properly. The docker file did not have access to the `requirements.txt`.
Tested by visiting https://gitpod.io/#https://github.com/avigad/mathematics_in_lean_source/pull/108 and verifying the container now loads.
> Fix gitpod setup

- MIL/C07_Hierarchies/S03_Subobjects.lean
This was introduced in the `Type _` -> `Type*` replacement.
> Fix a build error

- MIL/C07_Hierarchies/S03_Subobjects.lean
- lakefile.lean
For now we do not copy across the `autoImplicit` flag, as this would require changing the exercises.
It might still be worth doing this for a consistent experience with MIL vs mathlib contributions, but I will leave that for someone else to decide.
Depends on #109
> Copy across the build flags from mathlib 

- MIL/C02_Basics/S05_Proving_Facts_about_Algebraic_Structures.lean
- MIL/C03_Logic/S01_Implication_and_the_Universal_Quantifier.lean
- MIL/C04_Sets_and_Functions/S02_Functions.lean
Fix the following errors:
- `C02_Basics/S05_Proving_Facts_about_Algebraic_Structures.lean`:
Two exercises are stated with type like `a ≤ b → 0 ≤ b - a`, but at
this point, the `intro` tactic has not been introduced yet. Change it
to `(h : a ≤ b) : 0 ≤ b - a` to match the style of other example.
- `C03_Logic/S01_Implication_and_the_Universal_Quantifier.lean`:
`FnUb g b` should have been named `hgb` but not `hfb`.
- `C04_Sets_and_Functions/S02_Functions.lean`:
The correct theorem should be `f '' (s ∩ f ⁻¹' u) ⊆ f '' s ∩ u`, not
`f '' (s ∩ f ⁻¹' u) ⊆ f '' s ∪ u`.
> Fix minor error in the book

- MIL/C06_Structures/S01_Structures.lean
`cases` is no longer needed when writing definitions in terms of pattern matches, though mathlib still prefers to avoid doing so.
I think the mathlib community are still hesitant to use this feature, so I've added a hand-wave about more awkward goal views.
If leanprover/lean4#2042 is addressed, there will be more interesting things to say about this alternate spelling, but for now there isn't really.
> remove false remarks about structures that only held in Lean 3

- MIL/C03_Logic/S02_The_Existential_Quantifier.lean
- MIL/C07_Hierarchies/S01_Basics.lean
- MIL/C07_Hierarchies/S02_Morphisms.lean
- MIL/C07_Hierarchies/S03_Subobjects.lean
- lakefile.lean
This matches the stance taken by mathlib; it doesn't ban autoImplicit completely, but it does force files to acknowledge they are using it (of which there are only four).
This probably isn't the end of this story; I would recommend following up with a further PR (tracked by #115) to either:
* Change these files to not use `autoImplicit`s at all
* Update the explanatory text to explain their usage
> make autoImplicit opt-in

- MIL/C08_Groups_and_Rings/S01_Groups.lean
`open scoped Classical` means the same thing anyway, but is at least more idiomatic and easier to search for.
Of course I still think it's a bad idea to teach it at all, but that's a problem for another PR!
> Use `open scoped` not `local instance`

- MIL/C03_Logic/S04_Conjunction_and_Iff.lean
It is not true that obtain was used with the existential quantifier, so delete "which we used with the existential quantifier,"
> Update S04_Conjunction_and_Iff.lean correct reference to obtain

- MIL/C03_Logic/S02_The_Existential_Quantifier.lean
This example is about upper bounds, so ubfa makes more sense than lbfa
> Update S02_The_Existential_Quantifier.lean Fix typo ubfa lbfa

- MIL/C09_Topology/C09_Topology.rst
In three of the four phrasings, `x` tends to `a` and `f(x)` tends to `b`. This makes the fourth one consistent with the others.
> Swap two variables for consistency

- MIL/C08_Groups_and_Rings/S02_Rings.lean
The submodule / ideal distinction is a distraction; the real cause is that dot notation doesn't nest like this.
This worked in Lean 3 as `I.^Quotient.mk`, but I think that feature is gone.
> Fix an incorrect comment about dot notation

- user_repo_source/.devcontainer/Dockerfile
- user_repo_source/.devcontainer/devcontainer.json
- user_repo_source/README.md
I think Codespaces is a lot friendlier for new users: Gitpod requires new users to verify their phone number (and I believe Codespaces also gives new users more hours, but I'm not sure).
This code worked on two of my other repositories, (see e.g. [here](https://github.com/fpvandoorn/HausdorffSchoolLean)) but it's probably good to test it anyway.
Note: I just ran into a problem where opening a file in codespaces (in another repo) caused it to start recompiling mathlib. Closing and re-opening codespaces solved that issue.
> Feat: enable codespaces in user repo

- MIL/C07_Hierarchies/S01_Basics.lean
... instead of the Inv class from mathlib4.
> Fix typo to define Group₁ by extending Inv₁

- MIL/C08_Groups_and_Rings/S02_Rings.lean
See discussion in: https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/Mathematics.20in.20Lean.2C.20CRT.20-.20Notation.20confusion
> Use Π instead of ∀ for statement of Chinese Remainder Theorem

- MIL/C01_Introduction/S02_Overview.lean
(Issue: https://github.com/avigad/mathematics_in_lean_source/issues/189) Fix a minor typo - the example refers to `mul_add`, not `mul_left_comm`. 
```
lake exe cache get
lake build
pip install sphinx-rtd-theme==1.2.0rc4
scripts/mkall.py
make html
```
Locally succeeded (on OSX), and the html looks good.
> Fix minor typo in S02_Overview.lean

- user_repo_source/.vscode/extensions.json
I noticed while helping people do installation this morning that everyone had a pop-up about installing an necessary extension.
This PR copies and pastes the corresponding file from Mathlib, which I think successfully inhibits this pop-up. I haven't re-tested, however.
> chore: add extensions.json to prevent pop-up about unnecessary extension

- MIL/C05_Elementary_Number_Theory/S03_Infinitely_Many_Primes.lean
I would suggest removing it entirely but `Nat.dvd_sub` currently resides in the lean4 repo.
> Change the one reference to `dvd_sub` to `dvd_sub'`

- MIL/C04_Sets_and_Functions/S01_Sets.lean
Names of propositions `pge` and `primep` don't match when destructing `Nat.exists_infinite_primes`
> switch proposition names `pge` and `primep` in S01_Sets.lean

- MIL/C04_Sets_and_Functions/S03_The_Schroeder_Bernstein_Theorem.lean
In the proof of surjectivity of `sbFun`, injectivity of `f` is not needed. This eliminates a warning and makes things more symmetric with the proof of injectivity which does not require injectivity of `g`. This might be highlighted in the text as well.
> surjectivity of SB function does not require injectivity of f

- MIL/C05_Elementary_Number_Theory/S02_Induction_and_Recursion.lean
Lean's prelude and other textbooks such as Functional Programing in Lean and Theorem Proving in Lean all use `where` when defining inductive types, so I guess it's the recommended syntax (?)
> use `where` when defining inductive types

- MIL/C05_Elementary_Number_Theory/S02_Induction_and_Recursion.lean
The text just after the code snippet says
> The fact that we include `mul_comm` as a simplification rule deserves comment. It should seem dangerous to simplify with the identity `x * y = y * x`, which would ordinarily loop indefinitely.
But the snippet uses `rw` so this doesn't make sense.
> replace `rw` by `simp`

- MIL/C01_Introduction/S01_Getting_Started.lean
The Lean 4 VS Code extension now uses a different command and a VS Code SimpleBrowser to display online documentation.
> Update outdated VS Code command reference

- MIL/C05_Elementary_Number_Theory/S03_Infinitely_Many_Primes.lean
- MIL/C09_Topology/S02_Metric_Spaces.lean
- MIL/C09_Topology/S03_Topological_Spaces.lean
- MIL/C10_Differential_Calculus/S02_Differential_Calculus_in_Normed_Spaces.lean
This PR converts `refine'` to `refine` as prescribed by the linter warnings.
> Convert `refine'` to `refine`

- MIL/C06_Structures/S01_Structures.lean
- MIL/C06_Structures/S02_Algebraic_Structures.lean
- MIL/C06_Structures/S03_Building_the_Gaussian_Integers.lean
A bunch of typos in Chapter 6, and a suggestion to replace `apply` by `exact` at the end of `natAbs_norm_mod_lt`
> Typos in Chapter 06

- MIL/C07_Hierarchies/S01_Basics.lean
The placement of the final text block's `-/` causes it to be rendered in the textbook.
> Fix minor typographic error in S01_Basics.lean

- MIL/C07_Hierarchies/S02_Morphisms.lean
- MIL/C08_Groups_and_Rings/S02_Rings.lean
- `We still have bundles continuous functions` -> `We still have bundles of continuous functions`
- `are two ``.``s and so it will parse` -> `are two ``.``\s and so it will parse as`
The second one here is a bit strange, but rst usually requires a space after ``.
> Fix "bundles continuous functions" typo and minor `` parsing error

- MIL/C06_Structures/S03_Building_the_Gaussian_Integers.lean
Fixes to small rendering issues in C06S03. Also changes one instance of the wording from "concepts or machinery" to "concepts and machinery" to be consistent with usage below that.
> Fix minor typos and textbook rendering issues in C06S03

- MIL/C06_Structures/S02_Algebraic_Structures.lean
This no longer appears to be necessary with current versions of Lean.
Closes #255
> Structures: remove unnecessary names/sentence

- MIL/C05_Elementary_Number_Theory/S02_Induction_and_Recursion.lean
- MIL/C05_Elementary_Number_Theory/S03_Infinitely_Many_Primes.lean
- MIL/C10_Topology/S02_Metric_Spaces.lean
```
info: ././././MIL/C05_Elementary_Number_Theory/S02_Induction_and_Recursion.lean:201:20: The '∑ x in s, f x' notation is deprecated: please use '∑ x ∈ s, f x' instead:
info: ././././MIL/C05_Elementary_Number_Theory/S02_Induction_and_Recursion.lean:204:21: The '∏ x in s, f x' notation is deprecated: please use '∏ x ∈ s, f x' instead:
info: ././././MIL/C05_Elementary_Number_Theory/S02_Induction_and_Recursion.lean:207:28: The '∑ x in s, f x' notation is deprecated: please use '∑ x ∈ s, f x' instead:
info: ././././MIL/C05_Elementary_Number_Theory/S02_Induction_and_Recursion.lean:210:29: The '∏ x in s, f x' notation is deprecated: please use '∏ x ∈ s, f x' instead:
info: ././././MIL/C05_Elementary_Number_Theory/S02_Induction_and_Recursion.lean:220:22: The '∑ x in s, f x' notation is …
```
> chore: avoid deprecated notation (`∑ x in s, f x` and `∏ x in s, f x`)

- MIL/C07_Hierarchies/S03_Subobjects.lean
- MIL/C08_Groups_and_Rings/S01_Groups.lean
- MIL/C09_Linear_Algebra/S02_Subspaces.lean
- MIL/C10_Topology/S02_Metric_Spaces.lean
```
warning: ././././MIL/C07_Hierarchies/S03_Subobjects.lean:219:9: `Quotient.map₂'` has been deprecated: use `Quotient.map₂` instead
warning: ././././MIL/C08_Groups_and_Rings/S01_Groups.lean:658:48: `Quotient.out'` has been deprecated: use `Quotient.out` instead
warning: ././././MIL/C09_Linear_Algebra/S02_Subspaces.lean:208:3: `DirectSum.IsInternal.submodule_independent` has been deprecated: use `DirectSum.IsInternal.submodule_iSupIndep` instead
warning: ././././MIL/C10_Topology/S02_Metric_Spaces.lean:610:11: `Metric.isClosed_ball` has been deprecated: use `Metric.isClosed_closedBall` instead
```
> chore: avoid deprecated `Quotient.map₂`, `Quotient.out`, `submodule_independent` and `isClosed_ball`
